xcodeproj 'Torch/Torch.xcodeproj'
platform :ios, '6.0'
pod 'InnerBand', '~> 1.0.5'
pod 'RestKit', '~> 0.20.3'
pod 'ViewDeck', '~> 2.2.11'
pod 'MGBox2', '~> 2.0.0'
pod 'Reveal-iOS-SDK', '~> 0.9.1'
pod 'OCTotallyLazy', '~> 1.1.0'
pod 'MBProgressHUD', '~> 0.7'
pod 'DDProgressView', '~> 0.1'
pod 'Reachability', '~> 3.1.1'
